### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by Naheel-Azawy** [phillbush/lsd#1]
Hi, this is wonderful! To be clear about what I want, here's [how I get my bar info](https://github.com/Naheel-Azawy/naheel-dotfiles/blob/master/scripts/bar#L112). I was looking for a portable way as I'm switching window managers but had no clue how to do that. So what I see here is sort of a life saver.
However, every workspace I have has the following structure { name, visible, focused, urgent }. Is it possible to optionally add those info to lsd?
And a little bonus, is there any portable way to get notified whenever something change, like `i3-msg -t subscribe` or `bspc subscribe`?

**Comment by phillbush** [comment]
>is there any portable way to get notified whenever something change, like i3-msg -t subscribe or bspc subscribe

I think I can do that, and recompute the information whenever some property change.

>However, every workspace I have has the following structure { name, visible, focused, urgent }. Is it possible to optionally add those info to lsd?

Name is the desktop name? What visible, focused and urgent information are? An urgent desktop means that there is an urgent window in that desktop?

**Comment by Naheel-Azawy** [comment]
Yeah, name is the desktop name and urgent is a desktop with an urgent window.

The focused desktop is what you called the current desktop, the one with an asterisk. So that's already done.

Visible is if the desktop is visible in one monitor. So for example, if you have two monitors that have different desktops, one of them will be focused and visible. The other one will be only visible but not focused. Here's a screenshot of my bar. "1" is focused and visible, "10" is only visible, and others are neither focused nor visible.

![image](https://user-images.githubusercontent.com/5764614/106684009-aa547300-65d6-11eb-8bdb-43445b67b16f.png)

**Comment by phillbush** [comment]
The visible thing may be hard to implement as it would require querying monitor information.

I will use another character to indicate the urgent desktop (probably a `-`). If the current desktop is the urgent desktop I will make lsd only display that it is the current one (since the urgent window is already being displayed, there is no need to indicate that the current desktop is urgent).

I will replace the order of the stuff, from

```
*0:2
 1:1
 2:4
 3:0
```

To:



```
*2:name of desk #0
 1:name of desk #1
-4:name of desk #2
 0:name of desk #3
```

For the “watching mode” (when lsd watches for modification on the desktop properties), I will separate the desks information with a tab, so the above information will be:

```
*2:name of desk #0	1:name of desk #1	-4:name of desk #2	0:name of desk #3
```

Thus, each line will be a query on the desktop settings.

**Comment by phillbush** [comment]
Just added some stuff.  
Check if the urgent window and desktop names work for you.  
To use in the “watch mode” just invoke lsd with an option (such as `-w`, but any option works).  
More information on the README.

**Comment by Naheel-Azawy** [comment]
Wow dude you've done it quick!

For the visible thing, never mind, it's not a huge deal I guess. I can live without it.

I've just tried the latest commit, got a segmentation fault at `if (hints->flags & XUrgencyHint) {` line 127. Looks like `XGetWMHints()` is returning NULL. From the manual:

       The  XGetWMHints function reads the window manager hints and returns NULL if
       no WM_HINTS property was set on  the  window  or  returns  a  pointer  to  a
       XWMHints  structure  if  it succeeds.

Maybe it's something wrong with i3?

**Comment by phillbush** [comment]
Maybe a window did not set those hints.
I added a new commit that checks whether `hints` is null. It should fix this.

**Comment by Naheel-Azawy** [comment]
That fixed the segfault at `hints->flags`. But it doesn't seems to be actually detecting any urgent windows yet.
Also, there was still a segfault anyway but somewhere else. Following with gdb, `getdesknames()` appears to be behaving weirdly. `desknames` is not NULL, `len` seems to be double the actual number of desktops I have, and the elements are not accessible. I haven't messed around with X11 before so I'm not sure if something is wrong or I'm missing something.

Here're few stuff from gdb. Note that I actually have 7 desktops.

```
(gdb) display nnames
17: nnames = 14
(gdb) display desknames[0]
18: desknames = (char **) 0x55555555b8a0
(gdb) display desknames[1]
19: desknames[0] = 0x34003300320031 <error: Cannot access memory at address 0x34003300320031>
(gdb) display desknames[2]
20: desknames[1] = 0x2300380035 <error: Cannot access memory at address 0x2300380035>
(gdb) display desknames[3]
21: desknames[2] = 0x0
(gdb) display desknames[13]
22: desknames[3] = 0x21 <error: Cannot access memory at address 0x21>
(gdb) display desknames[10]
23: desknames[13] = 0x555555559010 "\002"
```

**Comment by phillbush** [comment]
So, I was using XGetWindowProperty(3) wrong.  It does not return an array of strings, each one being a desktop name. It actually returns a single string, containing all the names ending with `\0`. And the returned (`len`) is the length of the string, not the length of the array.

So, this is the actual structure of `desknames` containing the names of four desktops:

```
char *desknames = "Work\0Web\0Games\0Chat\0"
```

You can confirm that by displaying `(char *)desknames` on gdb(1).

I will fix this quickly in the next release. Sorry about that, I have never used XGetWindowProperty(3) to get a string property from a window, so I had no idea it works that way.

**Comment by phillbush** [comment]
Now I tested `lsd` in WindowMaker, a wm that sets desktop names, and it runs fine.
The window urgency problem should be solved now too.

**Comment by Naheel-Azawy** [comment]
Names are working pretty well now, thanks! But urgency is still not.

![image](https://user-images.githubusercontent.com/5764614/106794509-00262b00-666a-11eb-9ac2-530ce07bf39e.png)

**Comment by phillbush** [comment]
I tested here with `xdotool set_window --urgency 1 $WINID` to set the urgency on a window (replace that `1` with a `0` to unset it). And now lsd can detect urgency changes.  That other commit actually detected urgency states but not urgency changes.

**Comment by Naheel-Azawy** [comment]
My bad, yep I tested only with -w. Anyway, now it seems to be working nicely in both cases. But urgent windows stay urgent unless I explicitly set `xdotool set_window --urgency 0 $WINID`. Usually, by only moving the focus to the window the urgency disappears.

**Comment by phillbush** [comment]
Now lsd should work as expected even with `-w`, as it now can detect urgency changes.  

Thanks for trying `lsd`!

**Comment by Naheel-Azawy** [comment]
I actually want this for lemonbar too! It is exactly what I needed. My bar script is currently full of window manager dependent mess. This lsd can clean it up a lot. I also just found out about your "focus", seems nice I might give it a try as well.

For the urgency thing, it still doesn't seems to be working properly for me. But never mind, I might dig further into it and try to fix it. I'm just busy with tons of stuff, as usual... So expect pull requests someday soon, or maybe few years later.

Yeah and before I go, I like your work, do you mind sharing your bar script? Or maybe your dotfiles?

**Comment by phillbush** [comment]
>Yeah and before I go, I like your work, do you mind sharing your bar script? Or maybe your dotfiles?

Thanks! I am rewriting my dotfiles, writing some scripts and stuff to prepare a dotfiles repository I will share here on github soon.  For the bar, today I just moved into a barless desktop.  Now, when I change the desktop, a [xnotify](https://github.com/phillbush/xnotify/) notification will popup with a list of desktops.

Here's how my desktop is now without the bar.

![scrot](https://user-images.githubusercontent.com/63266536/106816056-b68b0f80-666c-11eb-9137-96431c2a4613.png)

Here I just moved to the fourth desktop of the first monitor (the second monitor has two desktops).

Unfortunately I `rm`'d my bar script, but I rewrote it into a notification script:

```
#!/bin/sh
# desk - change current desktop
# this file in public domain

getdesk() {
	lsd | awk -F '[-*: ]+' -v DIR="$1" '
		/^\*/ { curr = NR }
		      { wins[NR] = $2 }
		END   {
			for (i = curr - 1; wins[i] && i > 0; i--)
				;
			first = i
			for (i = curr; wins[i] && i <= NR; i++)
				;
			last = i - 1

			if (DIR == "prev") {
				if (wins[curr - 1])
					print curr - 2
				else
					print last
			} else if (DIR == "next") {
				if (wins[curr])
					print curr
				else
					print first
			} else {
				print last
			}
		}
	'
}

printdesk() {
	lsd | awk -F '[-*: ]' '
		BEGIN        { printf "SEC:9\tIMG:'$ICONPATH'/places/user-desktop.png\tTAG:desk\t" }
		NR > 1 && !n { printf " " }
		/^\*/        { printf "●";  n = 0 }
		/^ /         { printf "○";  n = 0 }
		$2 == 0      { printf "\t"; n = 1 }
		END          { print "" }
	'
}

case $1 in
prev)
	wmctrl -s $(getdesk prev)
	;;
next)
	wmctrl -s $(getdesk next)
	;;
last)
	wmctrl -s $(getdesk last)
	;;
[0-9]*)
	wmctrl -s $1
	;;
"+"[0-9]*)
	wmctrl -r :ACTIVE: -t $(echo $1 | cut -c2-)
	;;
esac
printdesk
```

And my sxhkd config file is this:

```
# Change desktop
mod1 + {1,2,3,4,5,6,7,8,9}
	desk {0,1,2,3,4,5,6,7,8,9} >"$XNOTIFY_FIFO"
mod1 + shift + {1,2,3,4,5,6,7,8,9}
	desk +{0,1,2,3,4,5,6,7,8,9} >"$XNOTIFY_FIFO"
mod1 + {Tab, shift + Tab}
	desk {next, prev} >"$XNOTIFY_FIFO"
mod1 + 0
	desk last >"$XNOTIFY_FIFO"
mod1 + d
	desk >"$XNOTIFY_FIFO"
```

In my window manager, the desktops are created on demand, just like on GNOME. When I log in there is only a single empty desktop.  When I open a window on it, my wm creates a new desktop, so I have two (one with a window and the other one empty).  If I create another window in the empty desktop, a new empty desktop is created, and when I close all windows from a desktop, this desktop is removed.

The `desk` script output information in the format read by `xnotify`.

Alt + Tab cycles to the next desktop, Alt + Shift + Tab to the previous, Alt + 0 go to the empty desktop in the focused monitor (there is only a single empty desktop for each monitor).

That's it, I think. In the next days (or weeks, idk) I may be sharing my dotfiles.

**Comment by Naheel-Azawy** [comment]
This makes me feel guilty of how messy my setup is. Extremely clean and nicely done. I like the idea of the GNOME-like desktops in particular. I'll probably adopt some of those ideas to my dots. The barless desktop is an idea that I thought about long time ago. The bar can be distracting sometimes, but still I don't see how I can survive without it. Maybe someday.
